version: "3.9"
services:
#  mysql:
#    image: mysql:8.0
#    restart: always
#    environment:
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=123456
#      - MYSQL_DB=test
#    ports:
#      - "3306:3306"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    environment:
#      - DB_SOURCE=mysql://root:123456@postgres:3306/test
#    depends_on:
#      - mysql
#    entrypoint:
#      [
#        "/app/wait-for.sh",
#        "--",
#        "/app/start.sh"
#      ]
    command: [ "/app/main" ]
