// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: cs_proto.proto

package cs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CMPing) Reset() {
	*x = CMPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CMPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMPing) ProtoMessage() {}

func (x *CMPing) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMPing.ProtoReflect.Descriptor instead.
func (*CMPing) Descriptor() ([]byte, []int) {
	return file_cs_proto_proto_rawDescGZIP(), []int{0}
}

func (x *CMPing) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SMPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SMPing) Reset() {
	*x = SMPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMPing) ProtoMessage() {}

func (x *SMPing) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMPing.ProtoReflect.Descriptor instead.
func (*SMPing) Descriptor() ([]byte, []int) {
	return file_cs_proto_proto_rawDescGZIP(), []int{1}
}

func (x *SMPing) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CMLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Password  string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *CMLogin) Reset() {
	*x = CMLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CMLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMLogin) ProtoMessage() {}

func (x *CMLogin) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMLogin.ProtoReflect.Descriptor instead.
func (*CMLogin) Descriptor() ([]byte, []int) {
	return file_cs_proto_proto_rawDescGZIP(), []int{2}
}

func (x *CMLogin) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CMLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SMLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode   *int32  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3,oneof" json:"err_code,omitempty"`
	ErrMsg    *string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3,oneof" json:"err_msg,omitempty"`
	AccountId *string `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3,oneof" json:"account_id,omitempty"`
}

func (x *SMLogin) Reset() {
	*x = SMLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMLogin) ProtoMessage() {}

func (x *SMLogin) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMLogin.ProtoReflect.Descriptor instead.
func (*SMLogin) Descriptor() ([]byte, []int) {
	return file_cs_proto_proto_rawDescGZIP(), []int{3}
}

func (x *SMLogin) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *SMLogin) GetErrMsg() string {
	if x != nil && x.ErrMsg != nil {
		return *x.ErrMsg
	}
	return ""
}

func (x *SMLogin) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

var File_cs_proto_proto protoreflect.FileDescriptor

var file_cs_proto_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x63, 0x73, 0x22, 0x1a, 0x0a, 0x06, 0x43, 0x4d, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x1a, 0x0a, 0x06, 0x53, 0x4d, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x44, 0x0a, 0x07,
	0x43, 0x4d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0x93, 0x01, 0x0a, 0x07, 0x53, 0x4d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1e,
	0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1c,
	0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x02, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01,
	0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x0a, 0x0a,
	0x08, 0x5f, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x63, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cs_proto_proto_rawDescOnce sync.Once
	file_cs_proto_proto_rawDescData = file_cs_proto_proto_rawDesc
)

func file_cs_proto_proto_rawDescGZIP() []byte {
	file_cs_proto_proto_rawDescOnce.Do(func() {
		file_cs_proto_proto_rawDescData = protoimpl.X.CompressGZIP(file_cs_proto_proto_rawDescData)
	})
	return file_cs_proto_proto_rawDescData
}

var file_cs_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cs_proto_proto_goTypes = []interface{}{
	(*CMPing)(nil),  // 0: cs.CMPing
	(*SMPing)(nil),  // 1: cs.SMPing
	(*CMLogin)(nil), // 2: cs.CMLogin
	(*SMLogin)(nil), // 3: cs.SMLogin
}
var file_cs_proto_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cs_proto_proto_init() }
func file_cs_proto_proto_init() {
	if File_cs_proto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cs_proto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CMPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CMLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cs_proto_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cs_proto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cs_proto_proto_goTypes,
		DependencyIndexes: file_cs_proto_proto_depIdxs,
		MessageInfos:      file_cs_proto_proto_msgTypes,
	}.Build()
	File_cs_proto_proto = out.File
	file_cs_proto_proto_rawDesc = nil
	file_cs_proto_proto_goTypes = nil
	file_cs_proto_proto_depIdxs = nil
}
